{{- if .Values.envRenderSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-env
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
{{- range $key, $val := .Values.envRenderSecret }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end -}}
{{- end }}